# 80: ACME + 跳转（浏览器访问也会先到 443，但证书续期需要 80）
server {
    listen 80;
    server_name dare.hestudy.com; # 你的域名

    # 1. Certbot 验证专用路径
    location ^~ /.well-known/acme-challenge/ {
        access_log off;
        root /var/www/certbot;
        try_files $uri =404; # 如果路径不存在，返回 404
    }

    # 2. 强制跳转 HTTPS (一旦证书生成后取消注释)
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
  listen 443 ssl;
  http2 on;
  server_name dare.hestudy.com;

  ssl_certificate     /etc/letsencrypt/live/dare.hestudy.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/dare.hestudy.com/privkey.pem;
  include /etc/nginx/ssl-params/options-ssl-nginx.conf;
  ssl_dhparam /etc/nginx/ssl-params/ssl-dhparams.pem;

  access_log off;
  error_log warn;

  location ^~ /api/sync {
    # 关闭代理重定向
    proxy_redirect off;
    proxy_pass http://vpn:1080;
    # 启用 HTTP/1.1 或 HTTP/2 
    proxy_http_version 1.1;
    
    # 必要的 Header 设置，确保 XHTTP 握手正常
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    # 升级为 WebSocket/Upstream 必须的 Header（XHTTP 依赖 HTTP 升级）
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    # 关闭缓冲和超时设置
    proxy_buffering off;
    client_max_body_size 0;
    proxy_read_timeout 3600s;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    # 处理 SPA 单页应用 (React/Vue) 的路由问题
    try_files $uri $uri/ /index.html; 
  }

  location ~ /(\.user\.ini|\.ht|\.git|\.svn|\.project|LICENSE|README\.md) {
    deny all;
  }

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all;
  }
}
