# 80: ACME + 跳转（浏览器访问也会先到 443，但证书续期需要 80）
server {
    listen 80;
    server_name www.zhaohuijian.com zhaohuijian.com; # 你的域名

    # 1. Certbot 验证专用路径
    location ^~ /.well-known/acme-challenge/ {
        access_log off;
        root /var/www/certbot;
        try_files $uri =404; # 如果路径不存在，返回 404
    }

    # 2. 强制跳转 HTTPS (一旦证书生成后取消注释)
    location / {
        return 301 https://www.zhaohuijian.com$request_uri;
    }
}
server {
    listen 443 ssl;
    http2 on;
    server_name www.zhaohuijian.com;

    ssl_certificate     /etc/letsencrypt/live/www.zhaohuijian.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.zhaohuijian.com/privkey.pem;
    include /etc/nginx/ssl-params/options-ssl-nginx.conf;
    ssl_dhparam /etc/nginx/ssl-params/ssl-dhparams.pem;

    access_log off;
    error_log warn;

    root /var/www/html; # 这里的路径必须在 Nginx 容器内也存在
    index index.php;

    # 处理 WordPress 请求
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

      # 处理 PHP 请求
    location ~ \.php$ {
        fastcgi_pass www-zhaohuijian-com:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;  # WordPress 识别 HTTPS
        include fastcgi_params;
        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
    }

    # 重写 wp-admin 请求
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    location ~* ^/wp-content/uploads/.*\.php$ {
        deny all;
    }
    # 防止对 WordPress 内部文件的访问
    location ~ /wp-admin/includes/ {
        deny all;
    }
    # 禁止访问 wp-includes/theme-compat/
    location ~ /wp-includes/theme-compat/ {
        deny all;
    }
    # 禁止访问 wp-includes/js/tinymce/langs/.*\.php
    location ~ /wp-includes/js/tinymce/langs/.*\.php {
        deny all;
    }
    # 禁用 xmlrpc.php
    location = /xmlrpc.php {
        deny all;
    }
    # 禁止访问 wp-config.php
    location = /wp-config.php {
        deny all;
    }
    # 处理权限控制插件
    rewrite /wp-content/uploads/_pda(\/.+)\.([A-Za-z0-9_@&+-]+)$ "/index.php?pda_v3_pf=$1&is_direct_access=true&file_type=$2" last;
    rewrite /private/([a-zA-Z0-9-_.]+)$ "/index.php?pda_v3_pf=$1" last;


    # 缓存图片资源
    location ~* \.(gif|jpg|jpeg|png|bmp|swf|flv|mp3|mp4|ico|webp)$ {
        # 增加搜索引擎白名单，防止图片在搜索结果中裂图
        valid_referers none blocked server_names *.zhaohuijian.com *.google.com *.baidu.com *.bing.com;
        
        if ($invalid_referer) {
            return 403;
        }

        # 性能优化
        expires 30d;
        access_log off;
        # 保持连接，减少握手消耗
        tcp_nodelay on; 
        # 设置强缓存
        add_header Cache-Control "public, max-age=2592000, immutable";
        
        # 解决部分浏览器跨域问题（如果是字体或需要被外部解析的资源）
        # add_header Access-Control-Allow-Origin *;
    }
    # 缓存静态资源
    location ~ .*\.(js|css)?$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public, max-age=604800";
    }
    # 防止对 WordPress 内部文件的访问
    location ~ /(\.user\.ini|\.ht|\.git|\.svn|\.project|LICENSE|README\.md) {
        deny all;
    }

    # 防止对 WordPress 内部文件的访问
    location ~ /\.ht {
        deny all;
    }

    # ACME 验证专用路径
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }
}